# Generated by Django 4.1.1 on 2022-10-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_fecha_nacimiento_persona_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fecha_creacion',
            new_name='fecha_nacimiento',
        ),
    ]
